language: php

dist: trusty

sudo: false

php:
  - 7.2
  - 7.3
  - 7.4
  
env:
  global:
    - DEFAULT=1

matrix:
  fast_finish: true

  include:
    - php: 7.2
      env: PHPSTAN=7 DEFAULT=0

before_script:
  - composer install
  - if [[ $PHPSTAN > 0 ]]; then composer require phpstan/phpstan; fi
  - composer require robotusers/commander;

script:
  - if [[ $DEFAULT = 1 ]]; then vendor/bin/phpunit --coverage-clover=coverage.xml; fi
  - if [[ $PHPCS = 1 ]]; then vendor/bin/phpcs -p --extensions=php ./src ./tests; fi
  - if [[ $PHPSTAN > 0 ]]; then vendor/bin/phpstan analyse ./src --level $PHPSTAN; fi

notifications:
  email: false

after_success:
    - bash <(curl -s https://codecov.io/bash)
