language: php

dist: trusty

sudo: false

php:
  - 5.6
  - 7.0
  - 7.1
  
env:
  global:
    - DEFAULT=1

matrix:
  fast_finish: true

  include:
    - php: 5.6
      env: PHPCS=1 DEFAULT=0
    - php: 7.1
      env: PHPSTAN=2 DEFAULT=0
    - php: 7.1
      env: PHPSTAN=7 DEFAULT=0
      
  allow_failures:
    - env: PHPCS=1 DEFAULT=0
    - env: PHPSTAN=7 DEFAULT=0

before_script:
  - composer install
  - if [[ $PHPSTAN > 0 ]]; then composer require phpstan/phpstan; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.1" ]]; then composer require robotusers/commander; fi

script:
  - if [[ $DEFAULT = 1 ]]; then vendor/bin/phpunit --coverage-clover=coverage.xml; fi
  - if [[ $PHPCS = 1 ]]; then vendor/bin/phpcs -p --extensions=php ./src ./tests; fi
  - if [[ $PHPSTAN > 0 ]]; then vendor/bin/phpstan analyse ./src --level $PHPSTAN; fi

notifications:
  email: false

after_success:
    - bash <(curl -s https://codecov.io/bash)
